version: '3.0'
services:
  httpd:
    image: httpd:2.4.57-alpine3.18
    volumes:
      - ./data:/usr/local/apache2/htdocs/
      - ./httpd/conf/php.conf:/usr/local/apache2/conf/extra/php.conf
      - ./httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 8080:80
  nginx:
    image: nginx
    entrypoint: ["echo", "nginx is disabled"]
  php:
    build:
      context: .
      dockerfile: php.docker
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./data:/usr/local/apache2/htdocs/
      - ./php/php.ini:/usr/local/etc/php/php.ini
  redis:
    image: redis:7.2.0-alpine3.18
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
  db:
    image: yobasystems/alpine-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
