services:
  nginx:
    image: nginx
    profiles:
      - dev
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/ssl:/etc/nginx/ssl
    ports:
      - "${NGINX_PORT}:80"
      - '443:443'
    depends_on:
      - apache
  apache:
    image: httpd:2.4.62-alpine3.20
    hostname: apache
    volumes:
      - $ROOT_DIR:/usr/local/apache2/htdocs/
      - ./services/apache/conf/php.conf:/usr/local/apache2/conf/extra/php.conf
      - ./services/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 80:80
    depends_on:
      - php
      - db
  php:
    build:
      context: .
      dockerfile: php.docker
      args:
        PHP_VERSION: ${PHP_VERSION}
        GD_WEBP: ${GD_WEBP}
        GD_FREE_TYPE: ${GD_FREE_TYPE}
    volumes:
      - $ROOT_DIR:/usr/local/apache2/htdocs/
      - ./services/php/php.ini:/usr/local/etc/php/php.ini
  redis:
    image: redis:7.4.0-alpine3.20
    command: redis-server --appendonly yes
    volumes:
      - ./services/redis:/data
  db:
    image: yobasystems/alpine-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./services/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
