version: '3.0'
services:
  apache2:
    image: httpd
    volumes:
      - ./data:/usr/local/apache2/htdocs/
      - ./docker-php.conf:/usr/local/apache2/conf/extra/docker-php.conf
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 8080:80
  php:
    build:
      context: .
      dockerfile: php.docker
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./data:/usr/local/apache2/htdocs/
      - ./php.ini:/usr/local/etc/php/php.ini
  redis:
    image: redis:3.2.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
